import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import NavigationBar from './NavigationBar'
import { getServerSession } from 'next-auth/next'
import { options } from './api/auth/[...nextauth]/options'
import CartIcon from './CartIcon'
import ItemsCartContrextProvicer from './contexts/itemsCarContext';

import excuteQuery from "@/app/db";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

var categories: any;

async function getCategories(){

  var res = await excuteQuery({ query: 'SELECT * FROM productsCategories', values: [] });
  
  console.log(res);

  //console.log(resultss);

  /*const res = await fetch('https://two70s4325.execute-api.sa-east-1.amazonaws.com/getCategories', {
      method: 'POST',
      cache: 'no-store'
  })

  if (!res.ok) {
      throw new Error('Failed to fetch data');
  }*/

  //var result = JSON.parse(res);

  categories = res;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  await getCategories();
  
  const session = await getServerSession(options);
  
  return (
    <html lang='es'>
      <head>
        <link rel="icon" type="image/x-icon" href="/images/logoComp.ico" />
      </head>
      <body className={inter.className}>
        <main>
          <ItemsCartContrextProvicer>
            <NavigationBar categories={categories} session={session}/>
            <div className='w-max h-20'></div>
            <CartIcon/>
            {children}
            <footer className="bg-gray-800 text-white py-8 mt-8">
              <div className="container mx-auto flex justify-between items-center">
                  
                  <div className="flex space-x-6">
                      <a href="#" className="text-gray-300 hover:text-white">Inicio</a>
                      <a href="#" className="text-gray-300 hover:text-white">Sobre nosotros</a>
                      <a href="#" className="text-gray-300 hover:text-white">Contacto</a>
                      <a href="#" className="text-gray-300 hover:text-white">Blog</a>
                  </div>
                  
                  <div className="flex space-x-4">
                      <a href="#" className="text-gray-300 hover:text-white">
                          <i className="fab fa-facebook"></i>
                      </a>
                      <a href="#" className="text-gray-300 hover:text-white">
                          <i className="fab fa-twitter"></i>
                      </a>
                      <a href="#" className="text-gray-300 hover:text-white">
                          <i className="fab fa-instagram"></i>
                      </a>
                      <a href="#" className="text-gray-300 hover:text-white">
                          <i className="fab fa-linkedin"></i>
                      </a>
                  </div>
              </div>
          </footer>

          </ItemsCartContrextProvicer>
        </main>
      </body>
    </html>
  );
}
